CREATE TABLE `editorialDrafts` (
	`id` varchar(36) NOT NULL,
	`generationKey` varchar(120) NOT NULL,
	`slot` enum('morning','intraday','close','breaking') NOT NULL,
	`title` varchar(240) NOT NULL,
	`body` text NOT NULL,
	`facts` text NOT NULL,
	`sources` text NOT NULL,
	`issues` text NOT NULL,
	`status` enum('draft','needs_review','approved','rejected','published') NOT NULL DEFAULT 'draft',
	`createdBy` varchar(160) NOT NULL,
	`reviewedBy` varchar(160),
	`reviewNote` text,
	`reviewedAt` timestamp,
	`publishedBy` varchar(160),
	`publishedChannel` varchar(80),
	`publishedUrl` text,
	`publishedAt` timestamp,
	`scheduledFor` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `editorialDrafts_id` PRIMARY KEY(`id`),
	CONSTRAINT `editorial_drafts_generation_key_idx` UNIQUE(`generationKey`)
);
