export type IndexConstituent = {
  ticker: string;
  name: string;
  assetType: "STOCK" | "REIT";
  index: "IBOV" | "IFIX";
  sector?: string;
  exchange: "B3";
  currency: "BRL";
};

// Official Ibovespa Theoretical Portfolio Constituents (86 stocks)
export const IBOVESPA_CONSTITUENTS: IndexConstituent[] = [
  { ticker: "ABEV3", name: "AMBEV S/A", assetType: "STOCK", index: "IBOV", sector: "Bebidas", exchange: "B3", currency: "BRL" },
  { ticker: "ALOS3", name: "ALLOS", assetType: "STOCK", index: "IBOV", sector: "Exploração de Imóveis", exchange: "B3", currency: "BRL" },
  { ticker: "ALPA4", name: "ALPARGATAS", assetType: "STOCK", index: "IBOV", sector: "Calçados", exchange: "B3", currency: "BRL" },
  { ticker: "ARZZ3", name: "AREZZO CO", assetType: "STOCK", index: "IBOV", sector: "Calçados", exchange: "B3", currency: "BRL" },
  { ticker: "ASAI3", name: "ASSAI", assetType: "STOCK", index: "IBOV", sector: "Comércio e Distribuição", exchange: "B3", currency: "BRL" },
  { ticker: "AZUL4", name: "AZUL", assetType: "STOCK", index: "IBOV", sector: "Transporte Aéreo", exchange: "B3", currency: "BRL" },
  { ticker: "B3SA3", name: "B3", assetType: "STOCK", index: "IBOV", sector: "Serviços Financeiros", exchange: "B3", currency: "BRL" },
  { ticker: "BBAS3", name: "BRASIL", assetType: "STOCK", index: "IBOV", sector: "Bancos", exchange: "B3", currency: "BRL" },
  { ticker: "BBDC3", name: "BRADESCO", assetType: "STOCK", index: "IBOV", sector: "Bancos", exchange: "B3", currency: "BRL" },
  { ticker: "BBDC4", name: "BRADESCO", assetType: "STOCK", index: "IBOV", sector: "Bancos", exchange: "B3", currency: "BRL" },
  { ticker: "BBSE3", name: "BBSEGURIDADE", assetType: "STOCK", index: "IBOV", sector: "Previdência e Seguros", exchange: "B3", currency: "BRL" },
  { ticker: "BEEF3", name: "MINERVA", assetType: "STOCK", index: "IBOV", sector: "Alimentos Processados", exchange: "B3", currency: "BRL" },
  { ticker: "BHIA3", name: "CASAS BAHIA", assetType: "STOCK", index: "IBOV", sector: "Comércio Varejista", exchange: "B3", currency: "BRL" },
  { ticker: "BPAC11", name: "BTGP BANCO", assetType: "STOCK", index: "IBOV", sector: "Bancos", exchange: "B3", currency: "BRL" },
  { ticker: "BRAP4", name: "BRADESPAR", assetType: "STOCK", index: "IBOV", sector: "Holdings Diversificadas", exchange: "B3", currency: "BRL" },
  { ticker: "BRFS3", name: "BRF SA", assetType: "STOCK", index: "IBOV", sector: "Alimentos Processados", exchange: "B3", currency: "BRL" },
  { ticker: "BRKM5", name: "BRASKEM", assetType: "STOCK", index: "IBOV", sector: "Petroquímicos", exchange: "B3", currency: "BRL" },
  { ticker: "CCRO3", name: "CCR SA", assetType: "STOCK", index: "IBOV", sector: "Concessões Rodoviárias", exchange: "B3", currency: "BRL" },
  { ticker: "CIEL3", name: "CIELO", assetType: "STOCK", index: "IBOV", sector: "Serviços Financeiros", exchange: "B3", currency: "BRL" },
  { ticker: "CMIG4", name: "CEMIG", assetType: "STOCK", index: "IBOV", sector: "Energia Elétrica", exchange: "B3", currency: "BRL" },
  { ticker: "CMIN3", name: "CSNMINERACAO", assetType: "STOCK", index: "IBOV", sector: "Mineração", exchange: "B3", currency: "BRL" },
  { ticker: "COGN3", name: "COGNA ON", assetType: "STOCK", index: "IBOV", sector: "Serviços Educacionais", exchange: "B3", currency: "BRL" },
  { ticker: "CPFE3", name: "CPFL ENERGIA", assetType: "STOCK", index: "IBOV", sector: "Energia Elétrica", exchange: "B3", currency: "BRL" },
  { ticker: "CPLE6", name: "COPEL", assetType: "STOCK", index: "IBOV", sector: "Energia Elétrica", exchange: "B3", currency: "BRL" },
  { ticker: "CRFB3", name: "CARREFOUR BR", assetType: "STOCK", index: "IBOV", sector: "Comércio e Distribuição", exchange: "B3", currency: "BRL" },
  { ticker: "CSAN3", name: "COSAN", assetType: "STOCK", index: "IBOV", sector: "Petróleo, Gás e Biocombustíveis", exchange: "B3", currency: "BRL" },
  { ticker: "CSNA3", name: "SID NACIONAL", assetType: "STOCK", index: "IBOV", sector: "Siderurgia", exchange: "B3", currency: "BRL" },
  { ticker: "CVCB3", name: "CVC BRASIL", assetType: "STOCK", index: "IBOV", sector: "Viagens e Lazer", exchange: "B3", currency: "BRL" },
  { ticker: "CYRE3", name: "CYRELA REALT", assetType: "STOCK", index: "IBOV", sector: "Construção Civil", exchange: "B3", currency: "BRL" },
  { ticker: "DXCO3", name: "DEXCO", assetType: "STOCK", index: "IBOV", sector: "Construção e Decoração", exchange: "B3", currency: "BRL" },
  { ticker: "EGIE3", name: "ENGIE BRASIL", assetType: "STOCK", index: "IBOV", sector: "Energia Elétrica", exchange: "B3", currency: "BRL" },
  { ticker: "ELET3", name: "ELETROBRAS", assetType: "STOCK", index: "IBOV", sector: "Energia Elétrica", exchange: "B3", currency: "BRL" },
  { ticker: "ELET6", name: "ELETROBRAS", assetType: "STOCK", index: "IBOV", sector: "Energia Elétrica", exchange: "B3", currency: "BRL" },
  { ticker: "EMBR3", name: "EMBRAER", assetType: "STOCK", index: "IBOV", sector: "Material Aeronáutico", exchange: "B3", currency: "BRL" },
  { ticker: "ENEV3", name: "ENEVA", assetType: "STOCK", index: "IBOV", sector: "Energia Elétrica", exchange: "B3", currency: "BRL" },
  { ticker: "ENGI11", name: "ENERGISA", assetType: "STOCK", index: "IBOV", sector: "Energia Elétrica", exchange: "B3", currency: "BRL" },
  { ticker: "EQTL3", name: "EQUATORIAL", assetType: "STOCK", index: "IBOV", sector: "Energia Elétrica", exchange: "B3", currency: "BRL" },
  { ticker: "EZTC3", name: "EZTEC", assetType: "STOCK", index: "IBOV", sector: "Construção Civil", exchange: "B3", currency: "BRL" },
  { ticker: "FLRY3", name: "FLEURY", assetType: "STOCK", index: "IBOV", sector: "Serviços Médicos", exchange: "B3", currency: "BRL" },
  { ticker: "GGBR4", name: "GERDAU", assetType: "STOCK", index: "IBOV", sector: "Siderurgia", exchange: "B3", currency: "BRL" },
  { ticker: "GOAU4", name: "GERDAU MET", assetType: "STOCK", index: "IBOV", sector: "Siderurgia", exchange: "B3", currency: "BRL" },
  { ticker: "GOLL4", name: "GOL", assetType: "STOCK", index: "IBOV", sector: "Transporte Aéreo", exchange: "B3", currency: "BRL" },
  { ticker: "HAPV3", name: "HAPVIDA", assetType: "STOCK", index: "IBOV", sector: "Serviços Médicos", exchange: "B3", currency: "BRL" },
  { ticker: "HYPE3", name: "HYPERA", assetType: "STOCK", index: "IBOV", sector: "Medicamentos", exchange: "B3", currency: "BRL" },
  { ticker: "IGTI11", name: "IGUATEMI S.A", assetType: "STOCK", index: "IBOV", sector: "Exploração de Imóveis", exchange: "B3", currency: "BRL" },
  { ticker: "IRBR3", name: "IRB BRASIL RE", assetType: "STOCK", index: "IBOV", sector: "Previdência e Seguros", exchange: "B3", currency: "BRL" },
  { ticker: "ITSA4", name: "ITAUSA", assetType: "STOCK", index: "IBOV", sector: "Holdings Diversificadas", exchange: "B3", currency: "BRL" },
  { ticker: "ITUB4", name: "ITAU UNIBANCO", assetType: "STOCK", index: "IBOV", sector: "Bancos", exchange: "B3", currency: "BRL" },
  { ticker: "JBSS3", name: "JBS", assetType: "STOCK", index: "IBOV", sector: "Alimentos Processados", exchange: "B3", currency: "BRL" },
  { ticker: "KLBN11", name: "KLABIN S/A", assetType: "STOCK", index: "IBOV", sector: "Papel e Celulose", exchange: "B3", currency: "BRL" },
  { ticker: "LREN3", name: "LOJAS RENNER", assetType: "STOCK", index: "IBOV", sector: "Comércio Varejista", exchange: "B3", currency: "BRL" },
  { ticker: "LWSA3", name: "LOCAWEB", assetType: "STOCK", index: "IBOV", sector: "Programas e Serviços", exchange: "B3", currency: "BRL" },
  { ticker: "MGLU3", name: "MAGAZ LUIZA", assetType: "STOCK", index: "IBOV", sector: "Comércio Varejista", exchange: "B3", currency: "BRL" },
  { ticker: "MRFG3", name: "MARFRIG", assetType: "STOCK", index: "IBOV", sector: "Alimentos Processados", exchange: "B3", currency: "BRL" },
  { ticker: "MRVE3", name: "MRV", assetType: "STOCK", index: "IBOV", sector: "Construção Civil", exchange: "B3", currency: "BRL" },
  { ticker: "MULT3", name: "MULTIPLAN", assetType: "STOCK", index: "IBOV", sector: "Exploração de Imóveis", exchange: "B3", currency: "BRL" },
  { ticker: "NTCO3", name: "NATURA", assetType: "STOCK", index: "IBOV", sector: "Cosméticos e Perfumaria", exchange: "B3", currency: "BRL" },
  { ticker: "PCAR3", name: "PAO DE ACUCAR", assetType: "STOCK", index: "IBOV", sector: "Comércio e Distribuição", exchange: "B3", currency: "BRL" },
  { ticker: "PETR3", name: "PETROBRAS", assetType: "STOCK", index: "IBOV", sector: "Petróleo e Gás", exchange: "B3", currency: "BRL" },
  { ticker: "PETR4", name: "PETROBRAS", assetType: "STOCK", index: "IBOV", sector: "Petróleo e Gás", exchange: "B3", currency: "BRL" },
  { ticker: "PETZ3", name: "PETZ", assetType: "STOCK", index: "IBOV", sector: "Comércio Varejista", exchange: "B3", currency: "BRL" },
  { ticker: "POSI3", name: "POSITIVO TEC", assetType: "STOCK", index: "IBOV", sector: "Equipamentos de TI", exchange: "B3", currency: "BRL" },
  { ticker: "PRIO3", name: "PETROCHOICE (PRIO)", assetType: "STOCK", index: "IBOV", sector: "Petróleo e Gás", exchange: "B3", currency: "BRL" },
  { ticker: "RADL3", name: "RAIADROGASIL", assetType: "STOCK", index: "IBOV", sector: "Medicamentos e Saúde", exchange: "B3", currency: "BRL" },
  { ticker: "RAIZ4", name: "RAIZEN", assetType: "STOCK", index: "IBOV", sector: "Biocombustíveis", exchange: "B3", currency: "BRL" },
  { ticker: "RDOR3", name: "REDE D'OR", assetType: "STOCK", index: "IBOV", sector: "Serviços Médicos", exchange: "B3", currency: "BRL" },
  { ticker: "RENT3", name: "LOCALIZA", assetType: "STOCK", index: "IBOV", sector: "Locação de Veículos", exchange: "B3", currency: "BRL" },
  { ticker: "RECV3", name: "PETRORECONCAVO", assetType: "STOCK", index: "IBOV", sector: "Petróleo e Gás", exchange: "B3", currency: "BRL" },
  { ticker: "SANB11", name: "SANTANDER BR", assetType: "STOCK", index: "IBOV", sector: "Bancos", exchange: "B3", currency: "BRL" },
  { ticker: "SBSP3", name: "SABESP", assetType: "STOCK", index: "IBOV", sector: "Água e Saneamento", exchange: "B3", currency: "BRL" },
  { ticker: "SLCE3", name: "SLC AGRICOLA", assetType: "STOCK", index: "IBOV", sector: "Agricultura", exchange: "B3", currency: "BRL" },
  { ticker: "SMTO3", name: "SAO MARTINHO", assetType: "STOCK", index: "IBOV", sector: "Açúcar e Álcool", exchange: "B3", currency: "BRL" },
  { ticker: "SOMA3", name: "GRUPO SOMA", assetType: "STOCK", index: "IBOV", sector: "Vestuário", exchange: "B3", currency: "BRL" },
  { ticker: "SUZB3", name: "SUZANO S.A.", assetType: "STOCK", index: "IBOV", sector: "Papel e Celulose", exchange: "B3", currency: "BRL" },
  { ticker: "TAEE11", name: "TAESA", assetType: "STOCK", index: "IBOV", sector: "Energia Elétrica", exchange: "B3", currency: "BRL" },
  { ticker: "TIMS3", name: "TIM", assetType: "STOCK", index: "IBOV", sector: "Telecomunicações", exchange: "B3", currency: "BRL" },
  { ticker: "TOTS3", name: "TOTVS", assetType: "STOCK", index: "IBOV", sector: "Software e TI", exchange: "B3", currency: "BRL" },
  { ticker: "UGPA3", name: "ULTRAPAR", assetType: "STOCK", index: "IBOV", sector: "Distribuição de Combustíveis", exchange: "B3", currency: "BRL" },
  { ticker: "USIM5", name: "USIMINAS", assetType: "STOCK", index: "IBOV", sector: "Siderurgia", exchange: "B3", currency: "BRL" },
  { ticker: "VALE3", name: "VALE", assetType: "STOCK", index: "IBOV", sector: "Mineração", exchange: "B3", currency: "BRL" },
  { ticker: "VAMO3", name: "GRUPO VAMOS", assetType: "STOCK", index: "IBOV", sector: "Locação de Máquinas", exchange: "B3", currency: "BRL" },
  { ticker: "VBBR3", name: "VIBRA", assetType: "STOCK", index: "IBOV", sector: "Distribuição de Combustíveis", exchange: "B3", currency: "BRL" },
  { ticker: "VIVT3", name: "TELEFONICA BR", assetType: "STOCK", index: "IBOV", sector: "Telecomunicações", exchange: "B3", currency: "BRL" },
  { ticker: "WEGE3", name: "WEG", assetType: "STOCK", index: "IBOV", sector: "Motores e Equipamentos Elétricos", exchange: "B3", currency: "BRL" },
  { ticker: "YDUQ3", name: "YDUQS PART", assetType: "STOCK", index: "IBOV", sector: "Serviços Educacionais", exchange: "B3", currency: "BRL" },
];

// Official IFIX Theoretical Portfolio Constituents (Top 100 Real Estate Funds)
export const IFIX_CONSTITUENTS: IndexConstituent[] = [
  { ticker: "ALZR11", name: "Alianza Trust Renda Imobiliária", assetType: "REIT", index: "IFIX", sector: "Híbrido", exchange: "B3", currency: "BRL" },
  { ticker: "BARI11", name: "Barigui Rendimento Imobiliário", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "BCFF11", name: "BTG Pactual Fundo de Fundos", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
  { ticker: "BCIA11", name: "Bradesco Carteira Imobiliária Ativa", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
  { ticker: "BCRI11", name: "Banestes Recebíveis Imobiliários", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "BIME11", name: "Briar FII Multifamily", assetType: "REIT", index: "IFIX", sector: "Residencial", exchange: "B3", currency: "BRL" },
  { ticker: "BLMG11", name: "BlueMacaw Logística", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "BPFF11", name: "Brasil Plural Fundo de Fundos", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
  { ticker: "BPML11", name: "BTG Pactual Shoppings", assetType: "REIT", index: "IFIX", sector: "Shoppings", exchange: "B3", currency: "BRL" },
  { ticker: "BRCO11", name: "Bresco Logística", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "BRCR11", name: "BC Fund Lajes Corporativas", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "BTAL11", name: "BTG Pactual Agro Logística", assetType: "REIT", index: "IFIX", sector: "Agronegócio", exchange: "B3", currency: "BRL" },
  { ticker: "BTLG11", name: "BTG Pactual Logística", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "BTRA11", name: "BTG Pactual Terras Agrícolas", assetType: "REIT", index: "IFIX", sector: "Agronegócio", exchange: "B3", currency: "BRL" },
  { ticker: "CACR11", name: "Cartesia Recebíveis Imobiliários", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "CARE11", name: "Brazilian Graveyard and Death Care", assetType: "REIT", index: "IFIX", sector: "Outros", exchange: "B3", currency: "BRL" },
  { ticker: "CBOP11", name: "Castello Branco Office Park", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "CPFF11", name: "Capitânia Fundo de Fundos", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
  { ticker: "CPTS11", name: "Capitânia Securities II", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "CVBI11", name: "VBI CRI", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "CXAG11", name: "Caixa Agências", assetType: "REIT", index: "IFIX", sector: "Agências de Bancos", exchange: "B3", currency: "BRL" },
  { ticker: "CXCE11", name: "Caixa Centro Empresarial", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "CXRI11", name: "Caixa Rio Bravo FII", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
  { ticker: "DEVA11", name: "Devant Recebíveis Imobiliários", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "EQIR11", name: "EQI Recebíveis Imobiliários", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "EURO11", name: "Europar FII", assetType: "REIT", index: "IFIX", sector: "Logística / Industrial", exchange: "B3", currency: "BRL" },
  { ticker: "EVBI11", name: "VBI Logística", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "FAED11", name: "Anhanguera Educacional FII", assetType: "REIT", index: "IFIX", sector: "Educacional", exchange: "B3", currency: "BRL" },
  { ticker: "FCFL11", name: "Campus Faria Lima", assetType: "REIT", index: "IFIX", sector: "Educacional", exchange: "B3", currency: "BRL" },
  { ticker: "FIIB11", name: "Industrial do Brasil", assetType: "REIT", index: "IFIX", sector: "Industrial", exchange: "B3", currency: "BRL" },
  { ticker: "FIIP11", name: "RB Capital Renda I", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "FISC11", name: "SC 401 FII", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "FMOF11", name: "Memorial Office", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "GALG11", name: "Guardian Logística", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "GGRC11", name: "GGR Covepi Renda", assetType: "REIT", index: "IFIX", sector: "Logística / Industrial", exchange: "B3", currency: "BRL" },
  { ticker: "GTWR11", name: "Green Towers", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "HCTR11", name: "Hectare CE", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "HFOF11", name: "Hedge Top FOFII3", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
  { ticker: "HGBS11", name: "Hedge Brasil Shopping", assetType: "REIT", index: "IFIX", sector: "Shoppings", exchange: "B3", currency: "BRL" },
  { ticker: "HGCR11", name: "CSHG Recebíveis Imobiliários", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "HGFF11", name: "CSHG Fundo de Fundos", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
  { ticker: "HGLG11", name: "CSHG Logística", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "HGPO11", name: "CSHG Prime Offices", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "HGRE11", name: "CSHG Real Estate", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "HGRU11", name: "CSHG Renda Urbana", assetType: "REIT", index: "IFIX", sector: "Renda Urbana", exchange: "B3", currency: "BRL" },
  { ticker: "HLOG11", name: "Hedge Logística", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "HOSI11", name: "HOSI FII", assetType: "REIT", index: "IFIX", sector: "Hospitalar", exchange: "B3", currency: "BRL" },
  { ticker: "HPDP11", name: "Hedge Shopping Parque Dom Pedro", assetType: "REIT", index: "IFIX", sector: "Shoppings", exchange: "B3", currency: "BRL" },
  { ticker: "HRDF11", name: "Hedge Renda de Desenvolvimento", assetType: "REIT", index: "IFIX", sector: "Desenvolvimento", exchange: "B3", currency: "BRL" },
  { ticker: "HSLG11", name: "HSI Logística", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "HSML11", name: "HSI Malls", assetType: "REIT", index: "IFIX", sector: "Shoppings", exchange: "B3", currency: "BRL" },
  { ticker: "HTMX11", name: "Hotel Maxinvest", assetType: "REIT", index: "IFIX", sector: "Hotelaria", exchange: "B3", currency: "BRL" },
  { ticker: "IRDM11", name: "Iridium Recebíveis Imobiliários", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "JSRE11", name: "JS Real Estate", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "KFOF11", name: "Kinea Fundo de Fundos", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
  { ticker: "KIPF11", name: "Kinea FII Índice de Preços", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "KNCA11", name: "Kinea Crédito Agro", assetType: "REIT", index: "IFIX", sector: "Agronegócio", exchange: "B3", currency: "BRL" },
  { ticker: "KNCR11", name: "Kinea Rendimentos Imobiliários", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "KNHY11", name: "Kinea High Yield CRI", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "KNIP11", name: "Kinea Índices de Preços", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "KNRE11", name: "Kinea II Real Estate", assetType: "REIT", index: "IFIX", sector: "Desenvolvimento", exchange: "B3", currency: "BRL" },
  { ticker: "KNRI11", name: "Kinea Renda Imobiliária", assetType: "REIT", index: "IFIX", sector: "Híbrido", exchange: "B3", currency: "BRL" },
  { ticker: "KNSC11", name: "Kinea Securities", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "LASC11", name: "Legatus Shoppings", assetType: "REIT", index: "IFIX", sector: "Shoppings", exchange: "B3", currency: "BRL" },
  { ticker: "LGCP11", name: "LOG CP Inter FII", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "MALL11", name: "Malls Brasil Plural", assetType: "REIT", index: "IFIX", sector: "Shoppings", exchange: "B3", currency: "BRL" },
  { ticker: "MANA11", name: "Manatí Capital Hedge Fund", assetType: "REIT", index: "IFIX", sector: "Híbrido", exchange: "B3", currency: "BRL" },
  { ticker: "MAXR11", name: "Max Retail", assetType: "REIT", index: "IFIX", sector: "Varejo", exchange: "B3", currency: "BRL" },
  { ticker: "MCCI11", name: "Mauá Capital Recebíveis", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "MFII11", name: "Mérito Desenvolvimento Imobiliário", assetType: "REIT", index: "IFIX", sector: "Desenvolvimento", exchange: "B3", currency: "BRL" },
  { ticker: "MGFF11", name: "Mogno Fundo de Fundos", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
  { ticker: "MINT11", name: "Mint Educacional", assetType: "REIT", index: "IFIX", sector: "Educacional", exchange: "B3", currency: "BRL" },
  { ticker: "MORE11", name: "More Real Estate FOF", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
  { ticker: "MXRF11", name: "Maxi Renda", assetType: "REIT", index: "IFIX", sector: "Híbrido", exchange: "B3", currency: "BRL" },
  { ticker: "NAVT11", name: "Navi Imobiliário Total Return", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
  { ticker: "NCHB11", name: "NCH Brasil Recebíveis", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "NEWU11", name: "Newport Renda Urbana", assetType: "REIT", index: "IFIX", sector: "Renda Urbana", exchange: "B3", currency: "BRL" },
  { ticker: "OUJP11", name: "Ourinvest JPP", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "PATL11", name: "Pátria Logística", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "PLCR11", name: "Plural Recebíveis", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "PORD11", name: "Polo FII Recebíveis", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "PQAG11", name: "Parque Anhangüera", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "PQDP11", name: "Parque Dom Pedro Shopping", assetType: "REIT", index: "IFIX", sector: "Shoppings", exchange: "B3", currency: "BRL" },
  { ticker: "QAGR11", name: "Quasar Agro", assetType: "REIT", index: "IFIX", sector: "Agronegócio", exchange: "B3", currency: "BRL" },
  { ticker: "RBCO11", name: "RB Capital Lajes Corporativas", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "RBED11", name: "RBR Educacional", assetType: "REIT", index: "IFIX", sector: "Educacional", exchange: "B3", currency: "BRL" },
  { ticker: "RBFF11", name: "Rio Bravo Fundo de Fundos", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
  { ticker: "RBHY11", name: "Rio Bravo Crédito Imobiliário High Yield", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "RBRP11", name: "RBR Properties", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "RBRR11", name: "RBR Rendimento High Grade", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "RBRX11", name: "RBR Plus Multiestratégia", assetType: "REIT", index: "IFIX", sector: "Híbrido", exchange: "B3", currency: "BRL" },
  { ticker: "RBRY11", name: "RBR Private Crédito Imobiliário", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "RBVA11", name: "Rio Bravo Renda Varejo", assetType: "REIT", index: "IFIX", sector: "Varejo", exchange: "B3", currency: "BRL" },
  { ticker: "RCFA11", name: "RCI Brasil", assetType: "REIT", index: "IFIX", sector: "Híbrido", exchange: "B3", currency: "BRL" },
  { ticker: "RCRB11", name: "Rio Bravo Renda Corporativa", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "RECT11", name: "REC Renda Imobiliária", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "RECX11", name: "REC Fundo de Fundos", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
  { ticker: "RELG11", name: "REC Logística", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "RNDP11", name: "BB Renda Corporativa", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "RNGO11", name: "Rio Negro", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "RRCI11", name: "RB Capital Rendimento", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "RSPD11", name: "RB Capital Desenvolvimento", assetType: "REIT", index: "IFIX", sector: "Desenvolvimento", exchange: "B3", currency: "BRL" },
  { ticker: "RZAG11", name: "Riza Agro", assetType: "REIT", index: "IFIX", sector: "Agronegócio", exchange: "B3", currency: "BRL" },
  { ticker: "RZAK11", name: "Riza Akin Crédito", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "RZTR11", name: "Riza Terrax", assetType: "REIT", index: "IFIX", sector: "Agronegócio", exchange: "B3", currency: "BRL" },
  { ticker: "SADI11", name: "Santander Renda de Aluguéis", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "SARE11", name: "Santander Renda Imobiliária", assetType: "REIT", index: "IFIX", sector: "Híbrido", exchange: "B3", currency: "BRL" },
  { ticker: "SDIL11", name: "SDI Logística", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "SDIP11", name: "SDI Properties", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "SPTW11", name: "SP Downtown", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "TGAR11", name: "TG Ativo Real", assetType: "REIT", index: "IFIX", sector: "Desenvolvimento", exchange: "B3", currency: "BRL" },
  { ticker: "URPR11", name: "Urca Prime Renda", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "VCRR11", name: "Vectis Renda Residencial", assetType: "REIT", index: "IFIX", sector: "Residencial", exchange: "B3", currency: "BRL" },
  { ticker: "VCRI11", name: "Vectis Crédito Imobiliário", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "VCJR11", name: "Vectis Juros Real", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "VGIR11", name: "Valora RE III", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "VGIP11", name: "Valora CRI Índice de Preço", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "VILG11", name: "Vinci Logística", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "VINO11", name: "Vinci Offices", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "VISC11", name: "Vinci Shopping Centers", assetType: "REIT", index: "IFIX", sector: "Shoppings", exchange: "B3", currency: "BRL" },
  { ticker: "VIUR11", name: "Vinci Imóveis Urbanos", assetType: "REIT", index: "IFIX", sector: "Renda Urbana", exchange: "B3", currency: "BRL" },
  { ticker: "VSHO11", name: "Votorantim Shopping", assetType: "REIT", index: "IFIX", sector: "Shoppings", exchange: "B3", currency: "BRL" },
  { ticker: "VSLH11", name: "Versalhes Recebíveis", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "VTLT11", name: "Votorantim Logística", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "VVPR11", name: "V2 Properties", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "XPCI11", name: "XP Crédito Imobiliário", assetType: "REIT", index: "IFIX", sector: "Títulos e Valores Mobiliários", exchange: "B3", currency: "BRL" },
  { ticker: "XPCM11", name: "XP Corporate Macaé", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "XPHT11", name: "XP Hoteis", assetType: "REIT", index: "IFIX", sector: "Hotelaria", exchange: "B3", currency: "BRL" },
  { ticker: "XPIN11", name: "XP Industrial", assetType: "REIT", index: "IFIX", sector: "Logística / Industrial", exchange: "B3", currency: "BRL" },
  { ticker: "XPLG11", name: "XP Log", assetType: "REIT", index: "IFIX", sector: "Logística", exchange: "B3", currency: "BRL" },
  { ticker: "XPML11", name: "XP Malls", assetType: "REIT", index: "IFIX", sector: "Shoppings", exchange: "B3", currency: "BRL" },
  { ticker: "XPPR11", name: "XP Properties", assetType: "REIT", index: "IFIX", sector: "Lajes Corporativas", exchange: "B3", currency: "BRL" },
  { ticker: "XPSF11", name: "XP Selection FOF", assetType: "REIT", index: "IFIX", sector: "Fundo de Fundos", exchange: "B3", currency: "BRL" },
];

export function getAllB3IndexConstituents(): IndexConstituent[] {
  const map = new Map<string, IndexConstituent>();
  for (const c of IBOVESPA_CONSTITUENTS) {
    map.set(c.ticker, c);
  }
  for (const c of IFIX_CONSTITUENTS) {
    map.set(c.ticker, c);
  }
  return Array.from(map.values());
}
